POST http://localhost:3000/api/admin/countries
Content-Type: application/json

[{
    "name": "Cote d Ivoire",
    "code": "CI",
    "flag": "https://flagcdn.com/w40/ci.png"
}]

###
http://localhost:3000/api/admin/countries