POST http://localhost:3000/api/admin/countries
Content-Type: application/json

[{
    "name": "Cote d Ivoire",
    "code": "CI",
    "flag": "https://flagcdn.com/w40/ci.png"
}]

###
http://localhost:3000/api/admin/countries

###
POST http://localhost:3000/api/admin/services
Content-Type: application/json

{
    "name": "Test Service",
    "description": "This is a test service",
    "image" : {
        "public_id": "teamac/services/thumbnails/sample_image",
        "version": 1697059200,
        "signature": "abcdef1234567890abcdef1234567890abcdef12",
        "width": 800,
        "height": 600,
        "format": "jpg",
        "resource_type": "image",
        "created_at": "2024-10-12T00:00:00Z",
        "tags": [],
        "bytes": 123456,
        "type": "upload",
        "etag": "abcdef1234567890abcdef1234567890",
        "placeholder": false,
        "url": "http://res.cloudinary.com/dqnpplwcg/image/upload/v1697059200/teamac/services/thumbnails/sample_image.jpg",
        "secure_url": "https://res.cloudinary.com/dqnpplwcg/image/upload/v1697059200/teamac/services/thumbnails/sample_image.jpg",
        "access_mode": "public",
        "original_filename": "sample_image"
    }
}

###
http://localhost:3000/api/admin/services

###
http://localhost:3000/api/admin/offers

###
http://localhost:3000/api/admin/stats

###
http://localhost:3000/api/offers/cmhl65s1g0003exn89zm3r6ro